# Template to print the command output on screen
---

- name: create directory
  command: echo {{item}}
  register: result1
# when: item.changed
# notify: some_handler
  loop:
      - one
      - two
  notify: some_handler
