AWSTemplateFormatVersion: "2010-09-09"
Description: "stack: create Security groups"

Parameters:
  ParameterGetVPC:
    Description: "Enter if there is any specific vpc"
    Type: String
    Default: vpc-01eb23096fae50cbb

# Mappings:
Resources:
  SecurityGroupSSHandHTTP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupSSHandHTTP
      GroupDescription: "This is custom security group"
      VpcId: !Ref ParameterGetVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      # SecurityGroupEgress:
      #   - IpProtocol: tcp
      #     FromPort: 22
      #     ToPort: 22
      #     CidrIp: 0.0.0.0/0
      #   - IpProtocol: tcp
      #     FromPort: 80
      #     ToPort: 80
      #     CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: SecurityGroupSSHandHTTP

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupSSH
      GroupDescription: "This is custom security group"
      VpcId: !Ref ParameterGetVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupSSH

  SecurityGroupHTTP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupHTTP
      GroupDescription: "This is custom security group"
      VpcId: !Ref ParameterGetVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupHTTP
Outputs:
  SecurityGroupSSHandHTTP:
    Description: Information about the custom security group
    Value: !Ref SecurityGroupSSHandHTTP
    Export:
      Name: SecurityGroupSSHandHTTP

  SecurityGroupSSH:
    Description: Information about the custom security group
    Value: !Ref SecurityGroupSSH
    Export:
      Name: SecurityGroupSSH

  SecurityGroupHTTP:
    Description: Information about the custom security group
    Value: !Ref SecurityGroupHTTP
    Export:
      Name: SecurityGroupHTTP
