
AWSTemplateFormatVersion: "2020-May-07"
Description: A sample template to provision Ec2
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-003cb5bde3420db79"
      InstanceType: t2.micro
      KeyName: key
    #   BlockDeviceMappings:
    #     -
    #       DeviceName: /dev/sdm
    #       Ebs:
    #         VolumeType: io1
    #         Iops: 200
    #         DeleteOnTermination: false
    #         VolumeSize: 20