---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Master stack: PathToMasterStackFile"
Parameters:
  GetEc2Image:
    Description: "Get default image"
    Type: String
    Default: ami-003cb5bde3420db79

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: key
      ImageId: !Ref GetEc2Image
      InstanceType: t2.micro
      Monitoring: false
      SubnetId: subnet-09b4cdff5d6d95614
      SecurityGroupIds:
        - !ImportValue SecurityGroupSSH
      Tags:
        - Key: Name
          Value: newEc2WithImports
