---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Master stack: PathToMasterStackFile"
Parameters:
  GetEc2Image:
    Description: "Get default image"
    Type: String
    Default: ami-003cb5bde3420db79

Mappings:
  GetImage:
    amazon:
      imageID: ami-0323c3dd2da7fb37d
    centos:
      imageID: ami-003cb5bde3420db79

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      # Type: AWS::CloudFormation::Init  # this syntax not working
      AWS::CloudFormation::Init:
        configSets:
          All:
            - config
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content: !Join
                - |+
                - - >-
                    <h1>Congratulations, you have successfully launched the AWS
                    CloudFormation sample.</h1>
              mode: "000644"
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
    Properties:
      KeyName: key
      # ImageId: !Ref GetEc2Image
      #ImageId: !FindInMap [GetImage, amazon, imageID]
      ImageId: ami-0323c3dd2da7fb37d
      InstanceType: t2.micro
      Monitoring: false
      SubnetId: subnet-09b4cdff5d6d95614
      SecurityGroupIds:
        - !ImportValue SecurityGroupSSHandHTTP
      Tags:
        - Key: Name
          Value: Ec2WithUserData
      UserData: !Base64
        "Fn::Join":
          - ""
          - - |
              #!/bin/bash -xe
            - |
              yum update -y aws-cfn-bootstrap
            - |
              # Install the files and packages from the metadata
            - "/opt/aws/bin/cfn-init -v "
            - "         --stack "
            - !Ref "AWS::StackName"
            - "         --resource myEC2Instance "
            - "         --configsets All "
            - |+

            - |
              # Signal the status from cfn-init
            - "/opt/aws/bin/cfn-signal -e $? "
            - "         --stack "
            - !Ref "AWS::StackName"
            - "         --resource myEC2Instance "
            - |+

    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
