---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Master stack: PathToMasterStackFile"
Parameters:
  GetEc2Image:
    Description: "Get default image"
    Type: String
    Default: ami-003cb5bde3420db79

Mappings:
  GetImage:
    amazon:
      imageID: ami-0323c3dd2da7fb37d
    centos:
      imageID: ami-003cb5bde3420db79

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: key
      # ImageId: !Ref GetEc2Image
      ImageId: !FindInMap [GetImage, amazon, imageID]
      InstanceType: t2.micro
      Monitoring: false
      SubnetId: subnet-09b4cdff5d6d95614
      SecurityGroupIds:
        - !ImportValue SecurityGroupSSHandHTTP
      Tags:
        - Key: Name
          Value: Ec2WithUserData

      UserData: !Base64
        "Fn::Join":
          - ""
          - - |
              #!/bin/bash -xe
              yum update -y aws-cfn-bootstrap
            - |
              # Install the files and packages from the metadata
            - "/opt/aws/bin/cfn-init -v "
            - "         --stack "
            - !Ref "AWS::StackName"
            - "         --resource myEC2Instance "
            - |+

            - |
              # Signal the status
            - "/opt/aws/bin/cfn-signal -e $? "
            - "         --stack "
            - !Ref "AWS::StackName"
            - "  --resource MyInstance"
            - |+

    CreationPolicy:
      ResourceSignal:
        Timeout: PT2M
        # Fn::Base64: !Sub |
        #   #!/bin/bash -ex
        #   yum update -y aws-cfn-bootstrap
        #   /opt/aws/bin/cfn-init --stack $    AWS::StackId} --resource myEC2Instance
        # Fn::Base64: !Sub |
        #   #!/bin/bash -ex
        #   yum update -y aws-cfn-bootstrap
        #   /opt/aws/bin/cfn-init --stack ${AWS::StackId} --resource myEC2Instance

    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content: |
                <h1> Inside index : using cloudFormation init </h1>
          commands:
            test1:
              command: systemctl status httpd >~/test.txt
            test2:
              command: systemctl restart httpd
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
