---
apiVersion: v1
kind: Service
metadata:
  name: alplineservice
  labels:
    app: webserverservice
spec:
  selector:
    app: webserver
  type: NodePort
  ports:
    - nodePort: 32001
      port: 8080
      targetPort: 8080
