---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: pod2
      image: docker-registry:5000/root/alpine-local:v1.0
      imagePullPolicy: IfNotPresent
      command:
        - /sbin/init
